version: '3'
services:
  proxy:
    image: traefik
    restart: unless-stopped
    command: --web --docker --docker.exposedByDefault=false --loglevel=info
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - ./traefik/traefik.toml:/traefik.toml
    ports:
     - "80:80"
     - "443:443"
  dcproxy:
    image: mf2c/dataclay-proxy:latest
    depends_on:
      - logicmodule1
    expose:
      - "6472"
  cimi:
    image: mf2c/cimi-server:2.1-SNAPSHOT
    depends_on:
      - logicmodule1
      - dcproxy
    environment:
      - DC_HOST=dcproxy
      - DC_PORT=6472
      - EPHEMERAL_DB_BINDING_NS=com.sixsq.slipstream.db.dataclay.loader
      - PERSISTENT_DB_BINDING_NS=com.sixsq.slipstream.db.dataclay.loader
    expose:
     - "8201"
    labels:
     - "traefik.enable=true"
     #- "traefik.frontend.headers.customRequestHeaders=slipstream-authn-info:"
     - "traefik.backend=cimi"
     - "traefik.frontend.rule=PathPrefix:/,/"
    volumes:
     - ringcontainer:/opt/slipstream/ring-container
     - ringcontainerexample:/opt/slipstream/ring-example
  rc:
    image: sixsq/ring-container:3.53-SNAPSHOT
    expose:
     - "5000"
    volumes:
     - ringcontainer:/opt/slipstream/ring-container
     - ringcontainerexample:/opt/slipstream/ring-example
    command: sh
  slalite:
    image: mf2c/sla-management:0.3.0
    expose:
     - "46030"
    environment:
     - CIMI_URL=https://proxy:443/api
  lmpostgres1:
    image: postgres:9.5.12
    env_file:
      - ./env/PG.environment
    command: -c fsync=off

  logicmodule1:
    image: "bscdataclay/logicmodule"
    depends_on: ["lmpostgres1"]
    ports:
      - "11034:1034"
    env_file:
      - ./env/PG.environment
      - ./env/LM.environment
    environment:
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      - POSTGRES_HOST=lmpostgres1
    volumes:
      - ./prop/global.properties:/usr/src/app/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/app/log4j2.xml:ro
  ds1postgres1:
    image: postgres:9.5.12
    env_file:
      - ./env/PG.environment
    command: -c fsync=off

  ds1java1:
    image: "bscdataclay/dsjava"
    depends_on: ["ds1postgres1", "logicmodule1"]
    ports:
      - 2127
    env_file:
      - ./env/PG.environment
      - ./env/DS.environment
      - ./env/LM.environment
    environment:
      - DATASERVICE_NAME=DS1
      - POSTGRES_HOST=ds1postgres1
    volumes:
      - ./prop/global.properties:/usr/src/app/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/app/log4j2.xml:ro

  COMPSs:
    image: mf2c/compss-mf2c:1.0
    expose:
     - 8080
    restart: unless-stopped
  service-manager:
    image: mf2c/service-manager:latest
    restart: unless-stopped
    depends_on:
      - cimi
    expose:
      - 46200
    ports:
      - 46200:46200
    environment:
      - JAVA_OPTS=-Xms32m -Xmx256m
  discovery:
    image: mf2c/discovery:latest
    depends_on:
      - cimi
    expose:
      - 46040
    cap_add:
      - NET_ADMIN
  policies:
    image: mf2c/policies:latest
    depends_on:
      - discovery
    # container_name: policies
    ports:
      - "46050"
      - "46051:46051"
      - "46052:46052"
  cau-client:
    image: mf2c/cau-client:latest
    depends_on:
#   assuming cau and leader cau are bootstrapped elsewhere
      - policies
    # container_name: cau-client
    expose:
      - 46065
#   please provide ip:port params for CAU and leader CAU
    environment:
      - CAU_URL=127.0.0.1:46400
      - LCAU_URL=127.0.0.1:46410
  identification:
    image: mf2c/identification:latest
    volumes:
      - mydata:/data
    expose:
      - 46060
  user-management:
    image: mf2c/user-management:latest
    expose:
      - "46300"
  lifecycle:
    image: mf2c/lifecycle
    expose:
      - "46000"
    ports:
      - "46000:46000"
    environment:
      - HOST_IP=
      - DATACLAY_EP=
      - WORKING_DIR_VOLUME=/tmp/compose_files
    volumes:
      - /tmp/compose_files:/tmp/compose_files
      - /var/run/docker.sock:/var/run/docker.sock
  resouce-categorization:
    image: mf2c/resource-categorization:latest
    depends_on:
      - cimi
    expose:
      - 46070
    privileged: true
  snaptemp:
    image: mf2c/snaptemp:latest
    command: sh /download.sh
    depends_on:
      - snap
  influxdb:
    image: influxdb
    expose:
      - "8086"
    volumes:
      - influx:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=snap
      - INFLUXDB_USER=snap
      - INFLUXDB_USER_PASSWORD=snap
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_USER_PASSWORD=admin
  snap:
    image: intelsdi/snap:precise
    ports:
      - "8181:8181"
    volumes: ['/proc:/proc_host', '/sys/fs/cgroup:/sys/fs/cgroup', '/var/run/docker.sock:/var/run/docker.sock']
    depends_on:
      - influxdb
    environment:
      - SNAP_VERSION=2.0.0
      - SNAP_LOG_LEVEL=2
  influxdb-analytics:
    image: influxdb:latest
    environment:
      - ADMIN_USER=analytics_engine
      - INFLUX_INIT_PWD=analytics_engine
      - PRE_CREATE_DB=analytics_engine_development
    volumes:
      # Data persistency
      - influx-analytics:/var/lib/influxdb
  analytics_engine:
    image: mf2c/analytics-engine:latest
    expose:
      - "46020"
    depends_on:
      - influxdb-analytics
    volumes:
      - ./analytics_engine.conf:/analytics_engine/analytics_engine.conf
  neo4j:
    image: neo4j:2.3.12
    volumes:
    - neo4j:/data
    ports:
    - "7475:7474" # expose the port for the console ui
    environment:
    - NEO4J_AUTH=neo4j/password # neo4j requires change from default password, should reflect landscape.cfg
  landscaper:
    image: mf2c/landscaper:latest
    volumes:
    - landscaper:/landscaper/data
    - ./landscaper.cfg:/landscaper/landscaper.cfg
    depends_on:
      - "neo4j"
    environment:
      - OS_TENANT_NAME=
      - OS_PROJECT_NAME=
      - OS_TENANT_ID=
      - OS_USERNAME=
      - OS_PASSWORD=
      - OS_AUTH_URL=
    command: ["/start.sh", "http://neo4j:7474"]
  web:
    image: mf2c/landscaper-api:latest
    volumes:
      - ./landscaper.cfg:/landscaper/landscaper.cfg
    ports:
      - "9001:9001"
    depends_on:
      - neo4j
      - landscaper



volumes:
  mydata: {}
  influx: {}
  influx-analytics: {}
  neo4j: {}
  landscaper: {}
  ringcontainer: {}
  ringcontainerexample: {}